# Generated by Django 4.2.7 on 2023-11-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wheel_size_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_size_name', models.CharField(max_length=50)),
                ('tyre_diameter', models.IntegerField()),
                ('wheel_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.wheel_size')),
            ],
        ),
    ]
