# Generated by Django 4.2.7 on 2023-11-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_cassette_chainrings_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='cassette_name',
            field=models.CharField(max_length=20),
        ),
    ]
