# Generated by Django 4.2.7 on 2023-11-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_cassette_cassette_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cassette',
            new_name='Cassettes',
        ),
    ]
