# Generated by Django 4.2.7 on 2023-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rename_cassette_cassettes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettes',
            name='s1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s11',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s12',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s13',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s14',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s15',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cassettes',
            name='s9',
            field=models.IntegerField(null=True),
        ),
    ]
