# Generated by Django 4.2.7 on 2023-11-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_cassettes_s1_cassettes_s10_cassettes_s11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassettes',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s10',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s11',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s12',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s13',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s14',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s15',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s7',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s8',
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='s9',
        ),
    ]
