# Generated by Django 4.2.7 on 2023-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_remove_cassettes_s1_remove_cassettes_s10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.BooleanField()),
                ('body', models.CharField(max_length=2044)),
                ('date_field', models.DateField()),
            ],
        ),
    ]
