# Generated by Django 4.2.7 on 2023-11-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_blog_title_alter_blog_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre_size',
            old_name='tyre_diameter',
            new_name='tyre_circumference',
        ),
    ]
