# Generated by Django 4.2.7 on 2023-11-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_rename_tyre_diameter_tyre_size_tyre_circumference'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=2048)),
                ('date', models.DateField()),
            ],
        ),
    ]
