# Generated by Django 4.2.7 on 2023-11-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='feedback_body',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='contact',
            new_name='feedback_contact',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='feedback_title',
        ),
    ]
