# Generated by Django 4.2.7 on 2023-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_rename_feedback_user_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('staff', models.BooleanField()),
                ('owner', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tyre_size',
            name='wheel_size',
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cassettes',
            name='sprockets',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='chainrings',
            name='chainring_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='contact',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Wheel_size',
        ),
    ]
