# Generated by Django 4.2.7 on 2023-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_bike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettes',
            name='user_generated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chainrings',
            name='user_generated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
